tags_config:
  - prob: 0.05
    types:
    - 构图.制图特效
    - 构图.图片类型
    - 构图.画风
  - prob: 0.07
    types:
    - 构图.色彩
  - prob: 0.1
    types:
    - 构图.视角
  - prob: 0.07
    types:
    - 构图.背景
  - prob: 0.4
    types:
    - 人文景观.位置.室内
    - 人文景观.位置.室外
    - 人文景观.位置.建筑物
    - 人文景观.城市
  - prob: 0.4
    types:
    - 自然景观.位置.室外
    - 自然景观.天空/气象
    - 自然景观.花卉
  - prob: 0.12
    types:
    - 人物.摆位
  - prob: 0.05
    types:
    - 人物.类型
  - prob: 0.9
    types:
    - 人物.胸部size
  - prob: 0.6
    types:
    - 人物.衣装
  - prob: 0.1
    types:
    - 人物.全身装饰
  - prob: 0.24
    types:
    - 人物.上身装饰
  - prob: 0.1
    types:
    - 人物.下身装饰
  - prob: 0.15
    types:
    - 人物.鞋袜
  - prob: 0.2
    types:
    - 人物.胸部
  - prob: 0.2
    types:
    - 人物.头发
  - prob: 0.3
    types:
    - 人物.头部饰品
  - prob: 0.1
    types:
    - 人物.耳朵
  - prob: 0.11
    types:
    - 人物.脖子
  - prob: 0.15
    types:
    - 人物.动作
  - prob: 0.15
    types:
    - 人物.面部
  - prob: 0.2
    types:
    - 物品
  - prob: 0.1
    types:
    - 人文景观.食物.主食
    - 人文景观.食物.乳制品
    - 人文景观.食物.水果
    - 人文景观.食物.糖果零食
    - 人文景观.食物.肉类与海鲜
    - 人文景观.食物.蔬菜与香料
    - 人文景观.食物.调味料
    - 人文景观.食物.谷制品
    - 人文景观.食物.饮料
  - prob: 0.5
    types:
    - Special

default_args:
  prompt: ''
  negative_prompt: nsfw, (worst quality, low quality:1.4), signature, watermark, username, nipple
  height: 512
  width: 512
  seed: -1
  steps: 20
  subseed: -1
  sampler_name: DPM++ 2M SDE Heun Karras
  cfg_scale: 8
  enable_hr: true
  denoising_strength: 0.6
  hr_scale: 2
  hr_second_pass_steps: 20
  hr_upscaler: Latent (nearest-exact)

xl_default_args:
  prompt: ''
  negative_prompt: nsfw
  height: 1024
  width: 1024
  seed: -1
  steps: 28
  subseed: -1
  sampler_name: DPM++ 2M SDE Heun Karras
  cfg_scale: 8
  enable_hr: false
  denoising_strength: 0.6

sdxl_models:
  - animexlXuebimix_v40
  - counterfeitxl_v10
  - FinalAnimeCG_mk2a2

xl_vae: sdxl_vae.safetensors
default_vae: model.vae.pt

sdw_url: http://127.0.0.1:8085